### PR TITLE
Added script to convert model to ONNX

### PR DESCRIPTION
**Pull request by vinhtq115**
This script helps user convert a pretrained weight to an ONNX file.

Usage: `python convert_to_onnx.py /path/to/exp/yaml /path/to/pretrained/weight /path/to/save/onnx`.

### CODE REVIEW

**Comment by azamatkhid** [comment]
@vinhtq115 hello! Is it working script now? @MhLiao are you planning to merge?) Thanks all =)

**Comment by vinhtq115** [comment]
> @vinhtq115 hello! Is it working script now? @MhLiao are you planning to merge?) Thanks all =)

Ofc it is

**Comment by azamatkhid** [comment]
@vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details

**Review by MhLiao — APPROVED** [review]

**Comment by vinhtq115** [comment]
> @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details

I haven’t tested with DCN yet.

**Comment by phamkhactu** [comment]
@MhLiao i have problem with convert_to_onnx. Many thank for your help!!
```
UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  height_out = (height + 2 * ctx.padding -
/workspace/DB/assets/ops/dcn/functions/deform_conv.py:175: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  width_out = (width + 2 * ctx.padding -
Segmentation fault (core dumped)

```
torch1.10.0+cuda113

**Comment by phamkhactu** [comment]
> DCN mo

Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??

**Comment by phamkhactu** [comment]
> 

Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??

**Comment by vinhtq115** [comment]
> Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??

You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.

**Comment by phamkhactu** [comment]
> > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> 
> You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.

@vinhtq115 Thank for your help. But I can not converted. I found that DB model convert to onnx in [cv2 version 4.5](https://docs.opencv.org/4.x/d4/d43/tutorial_dnn_text_spotting.html), it is a model reference from repo. I infer with cv2, the output  
image
Can you share how to (post process) merge polygon in a same line to union polygon line. Many thanks.

**Comment by sssimpleboy** [comment]
> > > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> > 
> > 
> > You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.
> 
> @vinhtq115 Thank for your help. But I can not converted. I found that DB model is converted to onnx in [cv2 version 4.5](https://docs.opencv.org/4.x/d4/d43/tutorial_dnn_text_spotting.html), it is a model reference from repo. I infer with cv2, the output image Can you share how to (post process) merge polygon in a same line to union polygon line. Many thanks.

in  td500_resnet50_deform_thre.yaml  , line 14 ?

**Comment by sssimpleboy** [comment]
> > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> 
> You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.

hello! when i try to test the .onnx , it failed.
image


> > @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details
> 
> I haven’t tested with DCN yet.

hello! thankyou. I make .noox successfully by your method.But it failed to inference by onnx. 
image

after onnxoptimizer 
image

Could you help me ? I don't know what is wrong.

**Comment by sssimpleboy** [comment]
> > > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> > 
> > 
> > You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.
> 
> hello! when i try to test the .onnx , it failed. image
> 
> > > @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details
> > 
> > 
> > I haven’t tested with DCN yet.
> 
> hello! thankyou. I make .noox successfully by your method.But it failed to inference by onnx. image
> 
> after onnxoptimizer image
> 
> Could you help me ? I don't know what is wrong.

image

image

**Comment by sssimpleboy** [comment]
> > > > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> > > 
> > > 
> > > You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.
> > 
> > 
> > hello! when i try to test the .onnx , it failed. image
> > > > @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details
> > > 
> > > 
> > > I haven’t tested with DCN yet.
> > 
> > 
> > hello! thankyou. I make .noox successfully by your method.But it failed to inference by onnx. image
> > after onnxoptimizer image
> > Could you help me ? I don't know what is wrong.
> 
> image
> 
> image

image

**Comment by vinhtq115** [comment]
> > > > > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> > > > 
> > > > 
> > > > You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.
> > > 
> > > 
> > > hello! when i try to test the .onnx , it failed. image
> > > > > @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details
> > > > 
> > > > 
> > > > I haven’t tested with DCN yet.
> > > 
> > > 
> > > hello! thankyou. I make .noox successfully by your method.But it failed to inference by onnx. image
> > > after onnxoptimizer image
> > > Could you help me ? I don't know what is wrong.
> > 
> > 
> > image
> > image
> 
> image

Seems like those are warning messages that can be ignored. Have you tried checking the result's shape?
I don't use `onnxoptimizer` so I have no clue about it.

**Comment by sssimpleboy** [comment]
> > > > > > Many thanks, but i don't how to config test script with non-DCN. Can you share how to configs??
> > > > > 
> > > > > 
> > > > > You can replace `backbone: deformable_resnet18` to `backbone: resnet18` in the config file. Available backbones are in `backbones/__init__.py`.
> > > > 
> > > > 
> > > > hello! when i try to test the .onnx , it failed. image
> > > > > > @vinhtq115 so deformable convolution layer is converted as well without any problem? sorry for asking for details
> > > > > 
> > > > > 
> > > > > I haven’t tested with DCN yet.
> > > > 
> > > > 
> > > > hello! thankyou. I make .noox successfully by your method.But it failed to inference by onnx. image
> > > > after onnxoptimizer image
> > > > Could you help me ? I don't know what is wrong.
> > > 
> > > 
> > > image
> > > image
> > 
> > 
> > image
> 
> Seems like those are warning messages that can be ignored. Have you tried checking the result's shape? I don't use `onnxoptimizer` so I have no clue about it.
there is no result in the end.

**Comment by sssimpleboy** [comment]
is there anything wrong with my code ?
"result=sess.run(['output'],{'input':img.numpy()})"
it is my first time to use onnx . By the way, have you built your .onnx successfully?

**Comment by sssimpleboy** [comment]
> is there anything wrong with my code ? "result=sess.run(['output'],{'input':img.numpy()})" it is my first time to use onnx . By the way, have you built your .onnx successfully?
It remind me "Non-zero status code returned while running ReorderInput node".But I can find nothing on the internet about ReorderInput....

**Comment by vinhtq115** [comment]
Try this after declaring `InferenceSession`.

```
inputs = {sess.get_inputs()[0].name: img}
outputs = sess.run(None, inputs)[0]
out = np.array(outputs)
print(out.shape)
```

**Comment by sssimpleboy** [comment]
> Try this after declaring `InferenceSession`.
> 
> ```
> inputs = {sess.get_inputs()[0].name: img}
> outputs = sess.run(None, inputs)[0]
> out = np.array(outputs)
> print(out.shape)
> ```

it didnt work.
image
image
I change it to 
image
image

**Comment by vinhtq115** [comment]
> > Try this after declaring `InferenceSession`.
> > ```
> > inputs = {sess.get_inputs()[0].name: img}
> > outputs = sess.run(None, inputs)[0]
> > out = np.array(outputs)
> > print(out.shape)
> > ```
> 
> it didnt work. image image I change it to image image

Oh I forgot. You must use numpy array as input. Don't convert it to torch's Tensor.

```
# Convert to ONNX input
image -= RGB_MEAN
image /= 255.
image = np.transpose(image, (2, 0, 1))
image = np.expand_dims(image, axis=0)
```

**Comment by sssimpleboy** [comment]
it didn't work ,and the information is as same as before.

**Comment by vinhtq115** [comment]
> it didn't work ,and the information is as same as before.

Can you send me the code you used for inferencing and the ONNX file?

**Comment by sssimpleboy** [comment]
of course ,but i don't know how to upload my file. I can only copy...

**Comment by sssimpleboy** [comment]
> of course ,but i don't know how to upload my file. I can only copy...

I need some time to learn it.

**Comment by sssimpleboy** [comment]
demo.py

`#!python3
import argparse
import os
import onnx
import torch
import cv2
import numpy as np
from experiment import Structure, Experiment
from concern.config import Configurable, Config
import math
import time

os.environ["CUDA_VISIBLE_DEVICES"] = '1'
def main():
    parser = argparse.ArgumentParser(description='Text Recognition Training')
    parser.add_argument('exp', type=str)
    parser.add_argument('--resume', type=str, help='Resume from checkpoint')
    parser.add_argument('--image_path', type=str,default='./datasets/ships/images/image_1.jpg', help='image path,要检测的图片位置')
    parser.add_argument('--result_dir', type=str, default='./demo_results/ships/', help='path to save results')
    parser.add_argument('--data', type=str,
                        help='The name of dataloader which will be evaluated on.')
    parser.add_argument('--image_short_side', type=int, default=736,
                        help='The threshold to replace it in the representers')
    parser.add_argument('--thresh', type=float,
                        help='The threshold to replace it in the representers')
    parser.add_argument('--box_thresh', type=float, default=0.6,   
                        help='The threshold to replace it in the representers')  # 是否为目标的阈值
    parser.add_argument('--visualize', action='store_true',
                        help='visualize maps in tensorboard')
    parser.add_argument('--resize', action='store_true',
                        help='resize')
    parser.add_argument('--polygon', action='store_true',
                        help='output polygons if true')
    parser.add_argument('--eager', '--eager_show', action='store_true', dest='eager_show',
                        help='Show iamges eagerly')

    args = parser.parse_args()
    args = vars(args)
    args = {k: v for k, v in args.items() if v is not None}

    conf = Config()
    experiment_args = conf.compile(conf.load(args['exp']))['Experiment']
    experiment_args.update(cmd=args)
    experiment = Configurable.construct_class_from_config(experiment_args)
    if args['image_path'][-4:] in ['.jpg','.png','jpeg']:
        Demo(experiment, experiment_args, cmd=args).inference(args['image_path'], args['visualize'])
    else:
        res=os.listdir(args['image_path'])
        num_of_pictures=len(res)
        start_time_all = time.time()
        for i in range(num_of_pictures):
            start_time=time.time()
            Demo(experiment, experiment_args, cmd=args).inference(args['image_path']+res[i], args['visualize'])
            print("Time: {:.2f} s / img".format(time.time() - start_time))
        print("Average Time: {:.2f} s /img".format((time.time() - start_time_all) / num_of_pictures))



class Demo:
    def __init__(self, experiment, args, cmd=dict()):
        self.RGB_MEAN = np.array([122.67891434, 116.66876762, 104.00698793])
        self.experiment = experiment
        experiment.load('evaluation', **args)
        self.args = cmd
        model_saver = experiment.train.model_saver
        self.structure = experiment.structure
        self.model_path = self.args['resume']


    def init_torch_tensor(self):
        # Use gpu or not
        torch.set_default_tensor_type('torch.FloatTensor')
        if torch.cuda.is_available():
            self.device = torch.device('cuda')
            torch.set_default_tensor_type('torch.cuda.FloatTensor')
        else:
            self.device = torch.device('cpu')

    def init_model(self):
        model = self.structure.builder.build(self.device)
        return model

    def resume(self, model, path):
        if not os.path.exists(path):
            print("Checkpoint not found: " + path)
            return
        print("Resuming from " + path)
        states = torch.load(
            path, map_location=self.device)
        print("type(model)",type(states))
        model.load_state_dict(states, strict=False)
        print("Resumed from " + path)

    def resize_image(self, img):
        height, width, _ = img.shape
        if height < width:
            new_height = self.args['image_short_side']    #把高调整为736
            new_width = int(math.ceil(new_height / height * width / 32) * 32)  #把宽按比例缩放     math.ceil 是向上取整
            #print("new_height,new_width   ",new_height,' ',new_width)
        else:
            new_width = self.args['image_short_side']   #把宽调整为736
            new_height = int(math.ceil(new_width / width * height / 32) * 32)  #把高按比例缩放     
        resized_img = cv2.resize(img, (new_width, new_height))
        return resized_img
        
    def load_image(self, image_path):
        img = cv2.imread(image_path, cv2.IMREAD_COLOR).astype('float32')
        original_shape = img.shape[:2]
        img = self.resize_image(img)
        img -= self.RGB_MEAN
        img /= 255.
        img = torch.from_numpy(img).permute(2, 0, 1).float().unsqueeze(0)   
        #from_numpy 就是从numpy转化成tensor
        #permute 是对维度翻转，比如以前是 1080*1920*3，转换后是3*1080*1920
        #unsqueeze(0)是增加一个维度，变成  (*,3,1080,1920)
        return img, original_shape
        
    def format_output(self, batch, output):
        batch_boxes, batch_scores = output
        for index in range(batch['image'].size(0)):
            original_shape = batch['shape'][index]
            filename = batch['filename'][index]
            result_file_name = 'res_' + filename.split('/')[-1].split('.')[0] + '.txt'
            result_file_path = os.path.join(self.args['result_dir'], result_file_name)
            boxes = batch_boxes[index]
            scores = batch_scores[index]
            if self.args['polygon']:
                with open(result_file_path, 'wt') as res:
                    for i, box in enumerate(boxes):
                        box = np.array(box).reshape(-1).tolist()
                        result = ",".join([str(int(x)) for x in box])
                        score = scores[i]
                        res.write(result + ',' + str(score) + "\n")
            else:
                with open(result_file_path, 'wt') as res:
                    for i in range(boxes.shape[0]):
                        score = scores[i]
                        if score < self.args['box_thresh']:
                            continue
                        box = boxes[i,:,:].reshape(-1).tolist()
                        result = ",".join([str(int(x)) for x in box])
                        res.write(result + ',' + str(score) + "\n")
        
    def inference(self, image_path, visualize=False):
        self.init_torch_tensor()
        
        model = self.init_model()
        
        self.resume(model,self.model_path)
        model.eval()

        all_matircs = {}
        img, original_shape = self.load_image(image_path)
        
        """
        img, original_shape = self.load_image(image_path)
        # original saved file with DataParallel
        
        
        
        state_dict = torch.load('./path-to-model-directory/td500_resnet50')
        #print(type(state_dict1))
        
        #print("state_dict.items",state_dict.items())
        
        # create new OrderedDict that does not contain `module.`
        from collections import OrderedDict
        new_state_dict = OrderedDict()
        for k, v in state_dict.items():
            name =k.replace('module.','',1) # remove `module.`
            #name =k[13:]
            #name=k
            new_state_dict[name] = v
        # load params
        model.load_state_dict(new_state_dict)
        """

        #img = np.random.randint(0, 255, size=(960, 960, 3), dtype=np.uint8)
        #img = img.astype(np.float32)
        #img = (img / 255. - 0.5) / 0.5  # torch style norm
        #img = img.transpose((2, 0, 1))
        #img = torch.from_numpy(img).unsqueeze(0).float()
        dynamic_axes = {'input': {0: 'batch_size', 2: 'height', 3: 'width'},
                        'output': {0: 'batch_size', 2: 'height', 3: 'width'}}
        with torch.no_grad():
            img = img.to(self.device)
            torch.onnx.export(model.model.module, img, './DB.onnx', input_names=['input'],
                              output_names=['output'], dynamic_axes=dynamic_axes, keep_initializers_as_inputs=False,
                              verbose=True, opset_version=11)
        #    torch.onnx.export(model.model.module,img,'./DB.onnx', export_params=True,
        #        opset_version=11,input_names=['in'],output_names=['out'],dynamic_axes={'in':[2,3],'out':[2,3]},example_outputs=model(img))
        #orch.onnx.export(model, img, './DB.onnx', example_outputs=model(img))
        #torch.onnx.export(model,img,'./DB_10.onnx', export_params=False,
        #    opset_version=11,input_names=['in'],output_names=['out'],dynamic_axes={'in':[2,3],'out':[2,3]},example_outputs=model(img))
        #print("img.shape",img.shape)
        print("finished!")
        batch = dict()
        batch['filename'] = [image_path]
        batch['shape'] = [original_shape]
        batch['image'] = img 
        print("img.shape",img.shape)
        with torch.no_grad():
            #print("type(model)",type(model))
            #torch.save(model,'./DB_10.pth')
            #model=torch.load('./DB_10.pth')
            #pred = model.forward(batch, training=False)
            pred=model(img)
            #print(pred.shape)
            #print("pred",pred[0,0,274,35])
            #print("self.structure.representer.thresh",self.structure.representer.thresh)
            output = self.structure.representer.represent(batch, pred, is_output_polygon=self.args['polygon']) 
            print("output",output)
            #print(self.args['result_dir'], image_path.split('/')[-1].split('.')[0]+'.jpg')
            
            if not os.path.isdir(self.args['result_dir']):
                os.mkdir(self.args['result_dir'])
            self.format_output(batch, output)
            
            if visualize and self.structure.visualizer:
                vis_image = self.structure.visualizer.demo_visualize(image_path, output)
                cv2.imwrite(os.path.join(self.args['result_dir'], image_path.split('/')[-1].split('.')[0]+'.jpg'), vis_image)
            print("yes")
if __name__ == '__main__':
    main()
`

**Comment by sssimpleboy** [comment]
onnx1.py
`
import onnx ,onnxruntime
import cv2
import numpy as np
import math
def resize_image(img):
        height, width, _ = img.shape
        if height < width:
            new_height = 736    #set hight to 736
            new_width = int(math.ceil(new_height / height * width / 32) * 32) 
            #print("new_height,new_width   ",new_height,' ',new_width)
        else:
            new_width = 736   #set width to 736
            new_height = int(math.ceil(new_width / width * height / 32) * 32)  
        resized_img = cv2.resize(img, (new_width, new_height))
        return resized_img


model=onnx.load("./DB1.onnx")
onnx.checker.check_model(model)
img = cv2.imread('./datasets/ships/images/image_1.jpg', cv2.IMREAD_COLOR).astype('float32')
img=resize_image(img)
MEAN=np.array([122.67891434, 116.66876762, 104.00698793])
img -= MEAN
#print("img.shape",img.shape,type(img))
img /= 255.
img = np.transpose(img, (2, 0, 1))

img = np.expand_dims(img, axis=0)
#img = torch.from_numpy(img).permute(2, 0, 1).float().unsqueeze(0)   
print("img.shape",img.shape,type(img))
sess=onnxruntime.InferenceSession("./DB1.onnx")

inputs = {sess.get_inputs()[0].name: img}
outputs = sess.run(None, inputs)[0]
out = np.array(outputs)
print(out.shape)
`

**Comment by sssimpleboy** [comment]
asd.py
`
import onnx
import onnxoptimizer  # pip install onnxoptimizer

onnx_model = onnx.load('./DB.onnx')
passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]
optimized_model = onnxoptimizer.optimize(onnx_model, passes)

onnx.save(optimized_model, './DB1.onnx')`

**Comment by sssimpleboy** [comment]
Thank you  ,I am very moved!!

**Comment by vinhtq115** [comment]
I tried both ONNX files and it's true that they are bugged.

Can you send me the config file you used?

**Comment by sssimpleboy** [comment]
I was chatting with leader just now . please  wait a  moment ,thank you

**Comment by sssimpleboy** [comment]
ok, I will have a try .thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinh Quang ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MhLiao/DB] Added script to convert model to ONNX (PR #322)





 
Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.

**Comment by sssimpleboy** [comment]
> Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.



> Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
could you tell the type of gpu and environment ?

**Comment by vinhtq115** [comment]
> > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> 
> > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > could you tell the type of gpu and environment ?

I ran on Google Colab. PyTorch version was v1.11.0. GPU was not used during the conversion.

**Comment by sssimpleboy** [comment]
> > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > 
> > 
> > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > > could you tell the type of gpu and environment ?
> 
> I ran on Google Colab. PyTorch version was v1.11.0. GPU was not used during the conversion.
OK,the problem is in my .pth or .onnx ?

**Comment by vinhtq115** [comment]
> > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > 
> > 
> > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > > could you tell the type of gpu and environment ?
> 
> I ran on Google Colab. PyTorch version was v1.11.0. GPU was not used during the conversion. OK,the problem is in my .pth or .onnx ?

I used your checkpoint and it converted to ONNX fine. I also tried tested the new ONNX file with a random input and it ran fine.

Since I still keep the ONNX file, is there anyway for me to send it to you?

**Comment by sssimpleboy** [comment]
> 
I thank you very much, you are so kind. And I want to make .onnx myslef,because  we may update the parameters and it will disturb you and spend your much time if I can't do it . If i failed to make .onnx .maybe I need your help ..    the checkpoint I sent to you works not well , and we don't need it now . Thank you~ ^_^

**Comment by sssimpleboy** [comment]
> > > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > > 
> > > 
> > > > Seems like your PyTorch version is too old. I converted with PyTorch v1.11.0 and it ran fine.
> > > > could you tell the type of gpu and environment ?
> > 
> > 
> > I ran on Google Colab. PyTorch version was v1.11.0. GPU was not used during the conversion. OK,the problem is in my .pth or .onnx ?
> 
> I used your checkpoint and it converted to ONNX fine. I also tried tested the new ONNX file with a random input and it ran fine.
> 
> Since I still keep the ONNX file, is there anyway for me to send it to you?

I succeed ！

**Comment by sssimpleboy** [comment]
> > it didn't work ,and the information is as same as before.
> 
> Can you send me the code you used for inference and the ONNX file?
In the  beginning of July ,I have succeed .Thank for your help !

**Pull request merged**
